-- Generated by SwisserAI. Type /img_9742_move in chat to play the animation.
-- The clip is stored under the bare name 'img_9742_move' (vanilla GTA convention:
-- the YCD <Hash> holds the joaat key, <Name> only the descriptive pack path), so
-- both the dict and the clip are just the resource name. Same string works in any
-- trainer (Menyoo etc.): dict = 'img_9742_move', anim = 'img_9742_move'.
local DICT = 'img_9742_move'
local CLIP = 'img_9742_move'

RegisterCommand('img_9742_move', function()
    RequestAnimDict(DICT)

    local tries = 0
    while not HasAnimDictLoaded(DICT) and tries < 200 do
        Wait(10)
        tries = tries + 1
    end

    if not HasAnimDictLoaded(DICT) then
        print('[img_9742_move] ERROR: anim dict failed to load. '
            .. 'Did you do a FULL server restart after dropping the resource? '
            .. 'Stream assets only register on server start, not on resource restart.')
        TriggerEvent('chat:addMessage', { args = { '^1[img_9742_move]', 'AnimDict konnte nicht geladen werden — Server komplett neu starten.' } })
        return
    end

    local ped = PlayerPedId()
    ClearPedTasks(ped)
    TaskPlayAnim(ped, DICT, CLIP, 8.0, -8.0, -1, 1, 0, false, false, false)
    Wait(300)

    if IsEntityPlayingAnim(ped, DICT, CLIP, 3) then
        print(('[img_9742_move] OK — playing clip %s'):format(CLIP))
    else
        print(('[img_9742_move] WARN — clip %s did not start. Open the .ycd in CodeWalker and check the clip name.'):format(CLIP))
        TriggerEvent('chat:addMessage', { args = { '^3[img_9742_move]', 'Animation startete nicht. Clip-Name in YCD pruefen.' } })
    end
end, false)
